"""Phase 1 orchestration: preprocess -> eligibility -> dev sample -> features -> audit.

Usage:
    python scripts/01_prepare_data.py            # dev subset (200 series)
    python scripts/01_prepare_data.py --final    # final subset (config final_n_series)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.data import make_features, preprocess, select_series, splits  # noqa: E402
from src.utils.config import load_config, resolve_path, set_seed  # noqa: E402


def write_audit_report(cfg, panel, sup, out_dir: Path) -> None:
    lines = [
        "# Feature audit report (auto-generated by scripts/01_prepare_data.py)",
        "",
        "Every feature and why it is available at forecast time (origin day t,",
        "targets t+1..t+7). Frozen rules: configs/data.yaml.",
        "",
        "## Origin-anchored historical features (use sales <= t only)",
    ]
    for c in make_features.ORIGIN_FEATURES:
        lines.append(f"- `{c}` — window/lag ends at the origin date")
    lines += [
        "",
        "## Target-anchored observable lags (t+h-lag <= t for all h <= 7; asserted in code)",
    ]
    for lag in make_features.TARGET_LAGS:
        lines.append(f"- `lag_{lag}` = sales(t+h-{lag})")
    lines += [
        "",
        "## Future-known covariates at target date (whitelist: calendar, holiday",
        "schedule, planned promotions — assumption stated in the paper)",
    ]
    for c in make_features.TARGET_FEATURES:
        lines.append(f"- `{c}`")
    lines += [
        "",
        "## Static metadata",
        "- `family`, `class`, `perishable`, `city`, `state`, `type`, `cluster`",
        "",
        "## Counts",
        f"- panel rows: {len(panel):,}",
        f"- supervised rows: {len(sup):,}",
        f"- series: {sup.groupby(['store_nbr', 'item_nbr'], observed=True).ngroups:,}",
        f"- origins: {sup['origin_date'].nunique()}",
    ]
    (out_dir / "feature_audit.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"audit report -> {out_dir / 'feature_audit.md'}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--final", action="store_true", help="use final_n_series instead of dev")
    args = ap.parse_args()

    cfg = load_config()
    set_seed(cfg["sampling"]["random_seed"])
    splits.validate_splits(cfg)

    preprocess.run(cfg)
    select_series.compute_eligibility(cfg)
    if args.final:
        series = select_series.stratified_sample(
            cfg, n=cfg["sampling"]["final_n_series"], out_name="series_final.parquet"
        )
        tag = "final"
    else:
        series = select_series.stratified_sample(cfg)
        tag = "dev"

    panel = make_features.build_daily_panel(cfg, series)
    processed = resolve_path(cfg["paths"]["processed_dir"])
    panel.to_parquet(processed / f"panel_{tag}.parquet", index=False)

    # supervised rows for all frozen origins: weekly training + OOF + folds + holdout
    fold_o = [o for f in splits.fold_origins(cfg).values() for o in f]
    oof_o = list(splits.oof_origins(cfg))
    train_o = list(
        pd.date_range(
            pd.Timestamp(cfg["analysis_period"]["start"]) + pd.Timedelta(days=90),
            min(oof_o) - pd.Timedelta(days=1),
            freq=cfg["forecast"]["train_origin_frequency"],
        )
    )
    origins = sorted(set(train_o + oof_o + fold_o))
    sup = make_features.make_supervised(panel, origins, cfg["forecast"]["horizon"])
    sup.to_parquet(processed / f"supervised_{tag}.parquet", index=False)
    print(f"supervised table: {len(sup):,} rows -> supervised_{tag}.parquet")

    write_audit_report(cfg, panel, sup, resolve_path(cfg["paths"]["results_dir"]))


if __name__ == "__main__":
    main()
